bundler_args: --without development
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - ruby-head
  - jruby
  - jruby-head
before_install:
  - gem update bundler
after_success:
  - CI=true TRAVIS=true coveralls --verbose
matrix:
  include:
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
